# Generated by Django 3.1.3 on 2020-11-24 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('specialisation', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('foundation', models.DateField()),
                ('employees', models.PositiveIntegerField(verbose_name='number of employees')),
                ('partnership', models.ManyToManyField(blank=True, related_name='_company_partnership_+', to='company_list.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=255)),
                ('age', models.PositiveSmallIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_list.company')),
            ],
        ),
    ]
