# Generated by Django 3.1.3 on 2020-11-24 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='employees',
        ),
    ]
